#ifndef _PAL3_STATEDATAMANAGER_H_
#define _PAL3_STATEDATAMANAGER_H_

#pragma once

#include "SustainableStateDataInstance.h"
#include "PluginUtility.h"
#include <string>
#include <sstream>

using std::string;
using std::stringstream;

class StateDataManager;

// File paths.
PAL3HOOK_VERIFIED_DATAVAR static const string sustainableStateDataFilePath = ".\\PLUGIN_3.0\\BaseData\\sustainableStateDataInstance.csv";

// Maximum data sizes.
const int maxSustainableStateDataSize = 300;

// Size of the buffer used to load the file data.
const int maxBufferSizeForLoadingData = 4096;

// MARK: The manager of state data, singleton
class StateDataManager
{
public:

	~StateDataManager();
	static StateDataManager* sharedInstance();

	// Data. Generated by function "loadData". DO NOT modify them!
	SustainableStateDataInstance *sustainableStateData; // Status slot 1 and 2
	unsigned int *sustainableStateIdentifierData; // Identifiers of status slot 1 and 2. Used for binary search 
	unsigned int sustainableStateDataSize;

	// Function
	// Load status slot 1 and 2 from the specific file.
	bool loadData();
	// Using binary search to find a instance related to the provided identifier.
	SustainableStateDataInstance* instanceForIdentifier(unsigned int identifier);
	
	// Utility
	// Get a fixed name for a status, including the layer information.
    // std::wstring getFixedName(StateDataRunningInfo *info);
	// Get the state instance for a specific running information.
	// SustainableStateDataInstance* stateInstanceForRunningInfo:(StateDataRunningInfo *info);
	// Generate a default description for status slot 1 and 2. If the size of the member "description" is greater than 1, this function will return it as a customized description instead of the default one.
	static string generateDescriptionForSustainableState(SustainableStateDataInstance *instance, stringstream ss);
	// Get the description for a specific custom trigger type.
	static string getDescriptionForCustomTriggerType(int index);
	// Get the description for a specific attack type.
	static string getDescriptionForAttackType(int index);
	// Get the description for a specific magic property.
	static string getDescriptionForMagicProperty(int index);
	// Get the description for a basic state.
	static string getDescriptionForBasicState(int index);
	// Get the description for a consumption type.
	static string getDescriptionForConsumptionType(int index);
	// Get the description for a basic action.
	static string getDescriptionForBasicAction(int index);
	// Get the description for a current state.
	static string getDescriptionForCurrentState(int index);
	// Get the description for a temporary state.
	static string getDescriptionForTemporaryState(int index);

	// Debug
	string printData();

private:
	
	StateDataManager();
	StateDataManager(const StateDataManager&);
	StateDataManager& operator = (const StateDataManager&);

	stringstream ss;

	PAL3HOOK_VERIFIED_DATAVAR static StateDataManager *initialInstance;
};

#endif